# BusyBox ha un footprint minimale 
FROM busybox:latest
# oppure: FROM ubuntu:22:04

# visualizza sempre e solo Hello, world! 
# ENTRYPOINT echo 'Hello, world!'

# all'avvio e' possibile specificare ulteriori frasi da visualizzare DOPO Hello, world! 
# ENTRYPOINT ["echo", "Hello, world!"]

# per default visualizza Hello, world!, ma potrebbe anche visualizzare qualcosa di diverso  
ENTRYPOINT ["echo"]
CMD ["Hello, world!"]

