Encoding.default_external = Encoding.find('Windows-1250')
Encoding.default_internal = Encoding.find('Windows-1250') 

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-22.04"
  config.vm.hostname = "web"

  config.vm.network "private_network", ip: "10.11.1.191", virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 80, host: 8081

  config.vm.provision :shell, path: "install-apache.sh"

end
