# -*- mode: ruby -*-
# vi: set ft=ruby :

# 
# Vagrantfile per un cluster Kubernetes composto 
# da tre VM (una per il control plane e due nodi worker) 
# e da una VM esterna al cluster per lo sviluppo. 
# 

Encoding.default_internal = Encoding.find('Windows-1250') 

KUBE_CLUSTER_CONTROL_PLANE_IP='10.11.1.71'

KUBE_CLUSTER_NODES = [
    {
        :name => "kube-1",
        :type => "control-plane",
        :box => "bento/ubuntu-22.04",
        :eth1 => "10.11.1.71",
        :httpport => "8081",
        :ingressport => "31081",
        :memory => "3072",
        :cpus => "3", 
        :cpuexecutioncap => "100" 
    },
    {
        :name => "kube-2",
        :type => "worker",
        :box => "bento/ubuntu-22.04",
        :eth1 => "10.11.1.72",
        :httpport => "8082",
        :ingressport => "31082",
        :memory => "3072",
        :cpus => "3", 
        :cpuexecutioncap => "100" 
    },
    {
        :name => "kube-3",
        :type => "worker",
        :box => "bento/ubuntu-22.04",
        :eth1 => "10.11.1.73",
        :httpport => "8083",
        :ingressport => "31083",
        :memory => "3072",
        :cpus => "3", 
        :cpuexecutioncap => "100" 
    },
    {
        :name => "kube-dev",
        :type => "dev",
        :box => "bento/ubuntu-22.04",
        :eth1 => "10.11.1.131",
        :gocdport => "8153",
        :memory => "2048",
        :cpus => "2", 
        :cpuexecutioncap => "100" 
    }
]

VAGRANTFILE_API_VERSION = "2"

ASW_RESOURCES='/home/asw/resources/'

IMAGE_BOX = "bento/ubuntu-22.04" 

POD_NETWORK_CIDR = "10.12.0.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

    # Configurazioni comuni.

    # Ubuntu 20.04 LTS 64 bit VirtualBox (Bento)
    config.vm.box = IMAGE_BOX

    # folder per i progetti Asw (/home/asw/projects)
    config.vm.synced_folder "../../projects/", "/home/asw/projects", :mount_options => ["dmode=777", "fmode=777"]

    # folder per le risorse condivise per gli ambienti Asw (/home/asw/resources) 
    config.vm.synced_folder "../../resources/", "/home/asw/resources", :mount_options => ["dmode=777", "fmode=777"]

    # folder per i dati condivisi per gli ambienti Asw (/home/asw/data) 
	# da usare per eventuali volumi docker 
    # config.vm.synced_folder "../../data/", "/home/asw/data", :mount_options => ["dmode=777", "fmode=777"]
	
    KUBE_CLUSTER_NODES.each do |opts|
        config.vm.define opts[:name] do |node|

            node.vm.box = opts[:box]
            # node.vm.box_version = opts[:box_version]
            node.vm.hostname = opts[:name]
            node.vm.network "private_network", ip: opts[:eth1], virtualbox__intnet: true
			
			node.vm.boot_timeout = 600
			
            node.vm.provider "virtualbox" do |v|
                v.name = opts[:name]
                v.customize ["modifyvm", :id, "--memory", opts[:memory]]
                v.customize ["modifyvm", :id, "--cpus", opts[:cpus]]
                v.customize ["modifyvm", :id, "--cpuexecutioncap", opts[:cpuexecutioncap]]
            end

            node.vm.network "forwarded_port", guest: 22, host: 2211, id: 'ssh', auto_correct: true
            node.ssh.forward_agent = true
            
            if opts[:httpport] 
				node.vm.network "forwarded_port", guest: 8080, host: opts[:httpport], id: 'http', auto_correct: true
			end
            if opts[:ingressport] 
				node.vm.network "forwarded_port", guest: 31080, host: opts[:ingressport], id: 'ingress', auto_correct: true
			end
            if opts[:gocdport] 
				node.vm.network "forwarded_port", guest: 8153, host: opts[:gocdport], id: 'gocd', auto_correct: true
			end

			# 
			# development tools 
			#
            if opts[:type] == "dev"
				# installa Java, Gradle e Maven 
				node.vm.provision :shell, :inline => 'apt-get update'
				node.vm.provision :shell, :inline => ASW_RESOURCES + "java/setup-open-jdk.sh"
				node.vm.provision :shell, :inline => ASW_RESOURCES + "java/setup-gradle.sh"
				node.vm.provision :shell, :inline => ASW_RESOURCES + "java/setup-maven.sh"
				# installa Python e alcune librerie per REST 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "python/setup-python.sh"
				node.vm.provision :shell, :inline => ASW_RESOURCES + "python/setup-python-rest-libraries.sh"
				
				# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
				# node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'				
            end

			# 
			# docker / containerd
			#
            if opts[:type] == "dev"
				# installa docker  
				node.vm.provision :shell, :inline => ASW_RESOURCES + "docker/prepare-docker.sh"
				node.vm.provision :shell, :inline => ASW_RESOURCES + "docker/setup-docker.sh"
            else # opts[:type] == "control-plane" || opts[:type] == "worker"
				# installa containerd  
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-containerd.sh"
            end

			# 
			# kubernetes 
			#
            if opts[:type] == "control-plane"
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/configure-kube-cluster-hosts.sh $1 $2 $3 $4"
					s.args = ["10.11.1.70", "kube-", 1, 2]
				end 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-kubernetes-kubeadm.sh"
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/start-kube-cluster-control-plane.sh $1"
					s.args = [POD_NETWORK_CIDR]
				end 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-helm.sh"
 				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/setup-kube-cluster-calico-network-addon.sh $1"
					s.args = [POD_NETWORK_CIDR]
				end 
				# ingress controller (ascolta su 80): 
                node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-kube-cluster-nginx-ingress-addon.sh"
				# in alternativa (ma ascolta solo su 31080); 
                # node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-kube-cluster-ingress-nginx-addon.sh"
            elsif opts[:type] == "worker"
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/configure-kube-cluster-hosts.sh $1 $2 $3 $4"
					s.args = ["10.11.1.70", "kube-", 1, 2]
				end 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-kubernetes-kubeadm.sh"
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/start-kube-cluster-worker.sh $1"
					s.args = [KUBE_CLUSTER_CONTROL_PLANE_IP]
				end 
            else # opts[:type] == "dev" 
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/configure-kube-cluster-dev-hosts.sh $1 $2 $3 $4"
					s.args = ["10.11.1.70", "kube-", 1, 2]
				end 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-kubernetes-kubeadm-client.sh"
				node.vm.provision "shell" do |s| 
					s.inline = ASW_RESOURCES + "kube-cluster/configure-kube-cluster-client.sh $1"
					s.args = [KUBE_CLUSTER_CONTROL_PLANE_IP]
				end 
				node.vm.provision :shell, :inline => ASW_RESOURCES + "kube-cluster/setup-helm.sh"
            end
			
			# crea un link simbolico alla cartella dei progetti asw nella cartella dell'utente di default 
			node.vm.provision :shell, :inline => 'ln -s /home/asw/projects projects'

			node.vm.provision "shell" do |s| 
				s.inline = ASW_RESOURCES + "done.sh $1"
				s.args = [ opts[:name] ]
			end 
			
        end

    end

end 