Encoding.default_internal = Encoding.find('Windows-1250')

Vagrant.configure("2") do |config|

  config.vm.box = "bento/ubuntu-20.04"
  config.vm.hostname = "web"

  config.vm.network "private_network", ip: "10.11.1.193", virtualbox__intnet: true
  config.vm.network "forwarded_port", guest: 80, host: 8083

  config.vm.provision :shell, path: "install-puppet.sh"

  # Install Puppet Agent 
  config.vm.provision :shell, path: "download-apache-puppet-modules.sh"

  # Provision with Puppet 
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "puppet/manifests"
    puppet.manifest_file = "init.pp"
    puppet.module_path = "puppet/modules"
	# puppet.options = "--verbose --debug"
  end

end
