version: "3"
volumes:
  order-service-data:
    driver: local
  product-service-data:
    driver: local
  order-validation-service-data:
    driver: local
  consul-data:
    driver: local
  kafka-data:
    driver: local
services:
  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: api-gateway
    image: localhost/api-gateway
    ports:
      - "8080:8080"
    deploy:
      replicas: 1
  consul:
    image: hashicorp/consul
    hostname: localhost
    volumes:
      - consul-data:/consul/data
    ports:
      - "8500:8500"
    deploy:
      replicas: 1
  order-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-service
    image: localhost/order-service
    deploy:
      replicas: 2
  order-validation-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: order-validation-service
    image: localhost/order-validation-service
    deploy:
      replicas: 2
  product-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: product-service
    image: localhost/product-service
    deploy:
      replicas: 2
  db-order-service:
    image: postgres
    volumes:
      - order-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ordermanager
    ports:
      - "8082:5432"
  db-product-service:
    image: postgres
    volumes:
      - product-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ordermanager
    ports:
      - "8083:5432"
  db-order-validation-service:
    image: postgres
    volumes:
      - order-validation-service-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ordermanager
    ports:
      - "8084:5432"
  kafka:
    image: docker.io/bitnami/kafka:3.6
    ports:
      - "9092:9092"
    volumes:
      - "kafka-data:/bitnami"
    environment:
      # KRaft settings
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      # Listeners
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true